ALTER TABLE INGREDIENT 
ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE INGREDIENT 
ALTER COLUMN name SET NOT NULL, 
ALTER COLUMN contains_lactose SET NOT NULL, 
ALTER COLUMN vegetarian SET NOT NULL, 
ALTER COLUMN vegan SET NOT NULL,
ALTER COLUMN gluten_free SET NOT NULL;

ALTER TABLE INGREDIENT 
ADD CONSTRAINT unique_name UNIQUE (name);
